name: attendanddiscriminate
dataset_name: opportunity
has_null: True
devices: ['cuda:0']
anno_json: [
  'data/opportunity/annotations/loso_sbj_0.json',
  'data/opportunity/annotations/loso_sbj_1.json',
  'data/opportunity/annotations/loso_sbj_2.json',
  'data/opportunity/annotations/loso_sbj_3.json',
]
dataset: {
  sens_folder: ./data/opportunity/raw/inertial,
  input_dim: 113,
  sampling_rate: 30,
  num_classes: 17,
  window_size: 60,
  window_overlap: 75,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  hidden_dim: 128,
  conv_kernels: 64,
  conv_kernel_size: 10,
  enc_layers: 2,
  enc_is_bidirectional: False,
  dropout: 0.5,
  dropout_rnn: 0.5,
  dropout_cls: 0.5,
  activation: 'ReLU', 
  sa_div: 1
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 100,
  beta: 0.0003,
  lr_cent: 0.001,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  train_batch_size: 100,
  test_batch_size: 1,
}