name: attendanddiscriminate
dataset_name: rwhar
has_null: False
devices: ['cuda:0']
anno_json: [
  'data/rwhar/annotations/loso_sbj_0.json',
  'data/rwhar/annotations/loso_sbj_1.json',
  'data/rwhar/annotations/loso_sbj_2.json',
  'data/rwhar/annotations/loso_sbj_3.json',
  'data/rwhar/annotations/loso_sbj_4.json',
  'data/rwhar/annotations/loso_sbj_5.json',
  'data/rwhar/annotations/loso_sbj_6.json',
  'data/rwhar/annotations/loso_sbj_7.json',
  'data/rwhar/annotations/loso_sbj_8.json',
  'data/rwhar/annotations/loso_sbj_9.json',
  'data/rwhar/annotations/loso_sbj_10.json',
  'data/rwhar/annotations/loso_sbj_11.json',
  'data/rwhar/annotations/loso_sbj_12.json',
  'data/rwhar/annotations/loso_sbj_13.json',
  'data/rwhar/annotations/loso_sbj_14.json',
]
dataset: {
  sens_folder: ./data/rwhar/raw/inertial,
  input_dim: 21,
  sampling_rate: 50,
  num_classes: 8,
  window_size: 100,
  window_overlap: 75,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  hidden_dim: 128,
  conv_kernels: 64,
  conv_kernel_size: 18,
  enc_layers: 2,
  enc_is_bidirectional: False,
  dropout: 0.5,
  dropout_rnn: 0.5,
  dropout_cls: 0.5,
  activation: 'ReLU', 
  sa_div: 1
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 100,
  beta: 0.0003,
  lr_cent: 0.001,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  train_batch_size: 100,
  test_batch_size: 1,
}