name: actionformer
dataset_name: rwhar
has_null: True
train_split: ['training']
val_split: ['validation']
two_stage: False
anno_json: [
  'data/rwhar/annotations/chunked/5/loso_sbj_0.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_1.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_2.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_3.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_4.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_5.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_6.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_7.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_8.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_9.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_10.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_11.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_12.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_13.json',
  'data/rwhar/annotations/chunked/5/loso_sbj_14.json',
]
dataset: {
  feat_folder: ./data/rwhar/processed/inertial_features/50_samples_50_overlap,
  sens_folder: ./data/rwhar/raw/inertial,
  sampling_rate: 50,
  file_prefix: ~,
  file_ext: .npy,
  feat_stride: 25,
  num_frames: 50,
  input_dim: 1050,
  num_classes: 8,
  downsample_rate: 1,
  max_seq_len: 2304,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7],
  default_fps: null,
  force_upsampling: False,
}
model: {
  model_name: LocPointTransformer,
  backbone_type: convTransformer,
  fpn_type: identity,
  backbone_arch: [2, 2, 5],
  scale_factor: 2,
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 10000]],
  n_head: 4,
  n_mha_win_size: 9,
  embd_kernel_size: 3,
  embd_dim: 512,
  embd_with_ln: True,
  fpn_dim: 512,
  fpn_with_ln: True,
  fpn_start_level: 0,
  head_dim: 512,
  head_kernel_size: 3,
  head_num_layers: 3,
  head_with_ln: True,
  max_buffer_len_factor: 8.0,
  use_abs_pe: False,
  use_rel_pe: False,
}
opt: {
  type: AdamW,
  momentum: 0.9,
  weight_decay: 0.05,
  learning_rate: 0.0001,
  epochs: 100,
  warmup: True,
  warmup_epochs: 5,
  schedule_type: cosine,
  schedule_steps: [],
  schedule_gamma: 0.1,    
}
loader: {
  train_batch_size: 2,
  test_batch_size: 1,
  num_workers: 4,
}
train_cfg: {
  center_sample: radius,
  center_sample_radius: 1.5,
  loss_weight: 1.0,
  cls_prior_prob: 0.01,
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  head_empty_cls: [],
  dropout: 0.0,
  droppath: 0.1,
  label_smoothing: 0.1,
}
test_cfg: {
  pre_nms_topk: 5000,
  pre_nms_thresh: 0.001,
  iou_threshold: 0.1,
  min_score: 0.0,
  max_seg_num: 2000,
  nms_method: 'soft',
  nms_sigma: 0.4,
  duration_thresh: 0.05,
  multiclass_nms: True,
  voting_thresh: 0.75,
  ext_score_file: null,
}